import os
import json
import pandas as pd
from dotenv import load_dotenv
from openai import OpenAI
import csv
import re
import io
import requests
import tarfile
from datetime import datetime

load_dotenv()
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

# ============================================================
# BOX DIMENSIONS — Montserrat font, calibrated from Canva
#
# ZERTIFIKAT heading : 15 chars/line  59pt  (fixed — never translated)
# CourseTitle        : 42 chars/line  21pt  (course name)
# Congratulations    : 45 chars/line  17pt  (1 line)
# Ausbildungsziel    : 43 chars/line  9.5pt (section label)
# Theorie/Praxis box : 66 chars/line  6.5pt (bullet lists)
# Absolventin        : 33 chars/line  10pt  (field label)
# Geprüft durch      : 32 chars/line  10pt  (field label)
#
# Wrapping uses char count (Montserrat — different font from other templates)
# ============================================================

THEORIE_MAX    = 66   # chars per line for Theorie/Praxis content
SUBTITLE_MAX   = 42   # CourseTitle box
CONGRATS_MAX   = 45   # Congratulations line
SECTION_MAX    = 43   # Ausbildungsziel label
FIELD_MAX      = 33   # Absolventin / Geprüft durch
MAX_BODY_LINES = 18   # hard limit — body box fits exactly 18 lines
BODY_MAX_LINES = 18  # hard limit — body box fits max 18 lines


def wrap_chars(text, max_chars, prefix="", continuation=""):
    """Simple char-count wrapping — used for Montserrat font boxes."""
    words = text.strip().split()
    lines, cur_words, cur_len = [], [], len(prefix)
    budget = max_chars - len(prefix)
    for word in words:
        sp = 1 if cur_words else 0
        if cur_len + sp + len(word) > budget and cur_words:
            pfx = prefix if not lines else continuation
            lines.append(pfx + ' '.join(cur_words))
            cur_words, cur_len = [word], len(continuation) + len(word)
            budget = max_chars - len(continuation)
        else:
            cur_words.append(word)
            cur_len += sp + len(word)
    if cur_words:
        pfx = prefix if not lines else continuation
        lines.append(pfx + ' '.join(cur_words))
    return '\n'.join(lines)


def build_bullet_list(section_title, items):
    """
    Build bullet list:
      Theorie:
      - Item 1
      - Item 2
    """
    lines = [section_title]
    for item in items:
        wrapped = wrap_chars(item, THEORIE_MAX, prefix="- ", continuation="  ")
        lines.append(wrapped)
    return '\n'.join(lines)


# ============================================================
# FIXED TRANSLATIONS — headings that stay consistent
# ============================================================

ZERTIFIKAT_TRANSLATIONS = {
    "Deutsch":     "ZERTIFIKAT",
    "Englisch":    "CERTIFICATE",
    "Türkisch":    "SERTİFİKA",
    "Polnisch":    "CERTYFIKAT",
    "Russisch":    "СЕРТИФИКАТ",
    "Italienisch": "CERTIFICATO",
    "Spanisch":    "CERTIFICADO",
    "Französisch": "CERTIFICAT",
    "Ungarisch":   "TANÚSÍTVÁNY",
    "Rumänisch":   "CERTIFICAT"
}

LANGUAGES = [
    "Deutsch", "Englisch", "Türkisch", "Polnisch", "Russisch",
    "Italienisch", "Spanisch", "Französisch", "Ungarisch", "Rumänisch"
]

# ============================================================
# GERMAN SOURCE CONTENT
# ============================================================

GERMAN_CONGRATULATIONS = "Herzlichen Glückwunsch zur bestandenen Prüfung!"
GERMAN_SECTION_LABEL   = "Ausbildungsziel:"
GERMAN_ABSOLVENTIN     = "Absolventin"
GERMAN_GEPRUEFT_DURCH  = "Geprüft durch"

GERMAN_THEORIE_TITLE = "Theorie:"
GERMAN_PRAXIS_TITLE  = "Praxis:"

# Theory and Praxis items are generated by GPT per course — not hardcoded


# ============================================================
# GPT TRANSLATION
# ============================================================

def count_body_lines(theorie_title, theorie_items, praxis_title, praxis_items):
    """Count total lines the body box will use."""
    body = (
        build_bullet_list(theorie_title, theorie_items)
        + "\n\n"
        + build_bullet_list(praxis_title, praxis_items)
    )
    return len(body.split('\n'))


def generate_german_topics(course_name, max_retries=2):
    """Generate German theory + praxis topics, ensuring body fits MAX_BODY_LINES."""
    item_budget = MAX_BODY_LINES - 3  # 18 - 1(Theorie:) - 1(blank) - 1(Praxis:) = 15

    for attempt in range(max_retries + 1):
        prompt = f"""Create a German training curriculum for the course "{course_name}" for a professional certificate.

CRITICAL CONSTRAINT — LINE LIMIT:
The body box fits exactly {MAX_BODY_LINES} lines total.
Structure: "Theorie:" (1 line) + theorie items + blank line (1) + "Praxis:" (1 line) + praxis items.
So theorie_items + praxis_items combined MUST be MAX {item_budget} items total.
Each item MUST be max 64 characters (it gets "- " prefix = 66 total, fits 1 line).
Items must be SHORT bullet points — not full sentences.
Include course-specific topics relevant to "{course_name}".

IMPORTANT: Do NOT repeat the full course name "{course_name}" inside bullet points.
For example if course is "Ayurveda Massage", write "Was ist Ayurveda?" not "Was ist die Ayurveda Massage Massage?"
Only use the course name when absolutely necessary and never duplicate words.

Return ONLY valid JSON:
{{
  "theorie_items": ["topic 1", "topic 2", "... max {item_budget - 2} theorie items ..."],
  "praxis_items": ["skill 1", "... 1-2 praxis items, total with theorie ≤ {item_budget} ..."]
}}"""

        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.3,
            max_tokens=800,
            response_format={"type": "json_object"}
        )
        try:
            data = json.loads(response.choices[0].message.content)
            theorie_items = data.get("theorie_items", [])
            praxis_items  = data.get("praxis_items",  ["Technik"])

            lines = count_body_lines(
                GERMAN_THEORIE_TITLE, theorie_items,
                GERMAN_PRAXIS_TITLE,  praxis_items
            )

            if lines <= MAX_BODY_LINES:
                return theorie_items, praxis_items

            if attempt < max_retries:
                print(f"\n    ⚠ {lines} lines (max {MAX_BODY_LINES}) — retrying...", end="")
                item_budget = MAX_BODY_LINES - 3 - (lines - MAX_BODY_LINES)
            else:
                # Truncate to fit
                print(f"\n    ⚠ truncating to {MAX_BODY_LINES} lines", end="")
                while count_body_lines(GERMAN_THEORIE_TITLE, theorie_items, GERMAN_PRAXIS_TITLE, praxis_items) > MAX_BODY_LINES:
                    if len(theorie_items) > 1:
                        theorie_items.pop()
                    elif len(praxis_items) > 1:
                        praxis_items.pop()
                    else:
                        break
                return theorie_items, praxis_items

        except Exception as e:
            print(f"  ⚠ topic generation error: {e}")
            return [], ["Technik"]

    return theorie_items, praxis_items


def translate_content(course_name, lang, theorie_items_de, praxis_items_de):
    """Step 2: Translate all content including the generated topics into target language."""
    theorie_numbered = "\n".join(f"{i+1}. {item}" for i, item in enumerate(theorie_items_de))
    praxis_numbered  = "\n".join(f"{i+1}. {item}" for i, item in enumerate(praxis_items_de))

    prompt = f"""Translate the following German certificate texts into {lang}.

STRICT RULES:
- Translate EVERYTHING into {lang}. Zero German words in output.
- Translate the course name "{course_name}" naturally into {lang}.
- Every field is a SINGLE LINE — no line breaks inside any field.
- "theorie_items" must have EXACTLY {len(theorie_items_de)} items.
- "praxis_items" must have EXACTLY {len(praxis_items_de)} items.
- Do NOT use opening punctuation like ¿ or ¡ anywhere — even in Spanish or other languages.

OUTPUT: Return ONLY valid JSON:

{{
  "course_name": "translated course name (title case)",
  "schulung_label": "translation of 'Schulung' (Training/Course)",
  "congratulations": "translated congratulations line — single line",
  "section_label": "translation of 'Ausbildungsziel:' (training objective:)",
  "theorie_title": "translation of 'Theorie:' (Theory:)",
  "theorie_items": ["item 1", "item 2", "... exactly {len(theorie_items_de)} items ..."],
  "praxis_title": "translation of 'Praxis:' (Practice:)",
  "praxis_items": ["item 1", "... exactly {len(praxis_items_de)} items ..."],
  "absolventin": "translation of 'Absolventin' (Graduate)",
  "geprueft_durch": "translation of 'Geprüft durch' (Examined by)"
}}

GERMAN TEXTS:
COURSE NAME: {course_name}
CONGRATULATIONS: {GERMAN_CONGRATULATIONS}
SECTION LABEL: {GERMAN_SECTION_LABEL}
THEORIE TITLE: {GERMAN_THEORIE_TITLE}
THEORIE ITEMS:
{theorie_numbered}
PRAXIS TITLE: {GERMAN_PRAXIS_TITLE}
PRAXIS ITEMS:
{praxis_numbered}
ABSOLVENTIN: {GERMAN_ABSOLVENTIN}
GEPRÜFT DURCH: {GERMAN_GEPRUEFT_DURCH}
"""

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
        max_tokens=2000,
        response_format={"type": "json_object"}
    )
    try:
        return json.loads(response.choices[0].message.content)
    except Exception as e:
        print(f"  ⚠ JSON parse error: {e}")
        return {}


def safe_filename(text):
    return re.sub(r'[^\w\s-]', '', text).strip().replace(' ', '_')


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":
    print("=" * 58)
    print("  Zertifikat Generator")
    print("=" * 58)
    print(f"  Theorie/Praxis box : {THEORIE_MAX} chars/line (6.5pt Montserrat)")
    print(f"  Congrats line      : {CONGRATS_MAX} chars/line (17pt)")
    print(f"  Section label      : {SECTION_MAX} chars/line (9.5pt)\n")

    course_name = input("Enter course name in German (e.g. Ayurveda Massage): ").strip()

    print(f"\nGenerating 10 languages for '{course_name}'...\n")

    # Step 1: Generate German theory/praxis topics for this course
    print("  Generating course-specific topics...", end=" ", flush=True)
    theorie_items_de, praxis_items_de = generate_german_topics(course_name)
    lines_de = count_body_lines(GERMAN_THEORIE_TITLE, theorie_items_de, GERMAN_PRAXIS_TITLE, praxis_items_de)
    print(f"✅  {len(theorie_items_de)} theory + {len(praxis_items_de)} praxis = {lines_de}/{MAX_BODY_LINES} lines")

    print(f"\n  Theory topics (DE):")
    for item in theorie_items_de:
        print(f"    - {item}")
    print()

    rows = []
    names_by_lang = {"Deutsch": course_name}

    for lang in LANGUAGES:
        print(f"  → {lang:<14}", end="", flush=True)

        if lang == "Deutsch":
            course_translated  = course_name
            congratulations    = GERMAN_CONGRATULATIONS
            section_label      = GERMAN_SECTION_LABEL
            theorie_title      = GERMAN_THEORIE_TITLE
            theorie_items      = theorie_items_de
            praxis_title       = GERMAN_PRAXIS_TITLE
            praxis_items       = praxis_items_de
            absolventin        = GERMAN_ABSOLVENTIN
            geprueft_durch     = GERMAN_GEPRUEFT_DURCH
            schulung_label     = "Schulung"
            data               = {"schulung_label": "Schulung"}
            print("(source — no API call)")
        else:
            data               = translate_content(course_name, lang, theorie_items_de, praxis_items_de)
            course_translated  = data.get("course_name",      course_name)
            congratulations    = data.get("congratulations",   GERMAN_CONGRATULATIONS).lstrip('¿¡«„‹»›')
            section_label      = data.get("section_label",     GERMAN_SECTION_LABEL).lstrip('¿¡«„‹»›')
            theorie_title      = data.get("theorie_title",     GERMAN_THEORIE_TITLE).lstrip('¿¡«„‹»›')
            theorie_items      = [i.lstrip('¿¡«„‹»›- ') for i in data.get("theorie_items", theorie_items_de)]
            praxis_title       = data.get("praxis_title",      GERMAN_PRAXIS_TITLE).lstrip('¿¡«„‹»›')
            praxis_items       = [i.lstrip('¿¡«„‹»›- ') for i in data.get("praxis_items",  praxis_items_de)]
            absolventin        = data.get("absolventin",        GERMAN_ABSOLVENTIN).lstrip('¿¡«„‹»›')
            geprueft_durch     = data.get("geprueft_durch",     GERMAN_GEPRUEFT_DURCH).lstrip('¿¡«„‹»›')
            print("✅")

        # Validate counts
        if len(theorie_items) != len(theorie_items_de):
            print(f"\n    ⚠ {lang}: theorie_items — expected {len(theorie_items_de)}, got {len(theorie_items)}")
        if len(praxis_items) != len(praxis_items_de):
            print(f"\n    ⚠ {lang}: praxis_items — expected {len(praxis_items_de)}, got {len(praxis_items)}")

        names_by_lang[lang] = course_translated

        # Build single body box — Theorie + blank line + Praxis
        body = (
            build_bullet_list(theorie_title, theorie_items)
            + "\n\n"
            + build_bullet_list(praxis_title, praxis_items)
        )

        # Count lines and warn if over limit
        body_lines = len(body.split('\n'))
        line_status = f"✅ {body_lines} lines" if body_lines <= BODY_MAX_LINES else f"⚠ {body_lines} lines (max {BODY_MAX_LINES}!)"
        if lang != "Deutsch":
            print(f"         body: {line_status}")

        rows.append({
            "Language":          lang,
            "CourseName":        course_translated,
            "Heading":           ZERTIFIKAT_TRANSLATIONS.get(lang, "ZERTIFIKAT"),
            "SubTitle":          f"{data.get('schulung_label', 'Schulung')} {course_translated}",
            "Congratulations":   congratulations,
            "SectionLabel":      section_label,
            "Body":              body,
            "Label_Absolventin": absolventin,
            "Label_Geprueft":    geprueft_durch,
        })

    df = pd.DataFrame(rows)
    timestamp   = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_name   = safe_filename(course_name)
    output_file = f"Zertifikat_{safe_name}_10Languages_{timestamp}.csv"
    df.to_csv(output_file, index=False, quoting=csv.QUOTE_ALL, encoding="utf-8-sig")

    print(f"\n✅  CSV saved: {output_file}")
    print(f"\n📋  Canva Field Mapping:")
    print(f"    Heading           → ZERTIFIKAT / CERTIFICATE text box")
    print(f"    SubTitle          → 'Schulung Ayurveda Massage' text box")
    print(f"    Congratulations   → congratulations line")
    print(f"    SectionLabel      → 'Ausbildungsziel:' label")
    print(f"    Body              → Theorie + Praxis bullet list (same box)")
    print(f"    Label_Absolventin → 'Absolventin' field label")
    print(f"    Label_Geprueft    → 'Geprüft durch' field label")
    print(f"\n📝  Translated course names:")
    for lang, name in names_by_lang.items():
        print(f"    {lang:<14} → {name}")